name: dockify

services:

  frontend:
    image: optimalte/dockify-frontend:latest
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    image: optimalte/dockify-backend:latest
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data
      - poses_vol:/app/app/static/poses
      - previews_vol:/app/app/static/previews
      - targets_vol:/app/app/static/targets
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  poses_vol:
  previews_vol:
  targets_vol:
